"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., Example3.v1.tsx).
 * To stop versioning this component, run: npx uifork promote Example3 <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./Example3.versions"

export default function Example3(props: any) {
  return (
    <ForkedComponent
      id="Example3"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
