/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., Example1.v1.tsx).
 * To stop versioning this component, run: uifork promote Example1 <version-id>
 */
import { BranchedComponent } from "uifork";
import { VERSIONS } from "./Example1.versions";

export default function Example1(props: any) {
  return <BranchedComponent id="Example1" versions={VERSIONS} props={props} />;
}

export { VERSIONS };
