/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote Example1 <version-id>
 */
import Example1V1 from "./Example1.v1"
import Example1V2 from "./Example1.v2"
export const VERSIONS = {
  "v1": {
    render: Example1V1,
    label: "",
  },
  "v2": {
    render: Example1V2,
    label: "",
  },
}
