/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote Example3 <version-id>
 */
import Example3V1 from "./Example3.v1"
import Example3V2 from "./Example3.v2"
export const VERSIONS = {
  "v1": {
    render: Example3V1,
    label: "",
  },
  "v2": {
    render: Example3V2,
    label: "",
  },
}
