const fs = require("fs");
const path = require("path");
const { VersionSync } = require("./watch");
const { toPascalCaseIdentifier } = require("./component-naming");
const { detectComponentExport } = require("./detect-export");

class UISwitcherScaffold {
  /**
   * @param {string} filePath
   * @param {boolean} shouldWatch
   * @param {{ exportName?: string }} options
   */
  constructor(filePath, shouldWatch = true, options = {}) {
    this.shouldWatch = shouldWatch;
    this.originalFilePath = path.resolve(filePath);

    if (!fs.existsSync(this.originalFilePath)) {
      console.error(`File does not exist: ${this.originalFilePath}`);
      process.exit(1);
    }

    const parsedPath = path.parse(this.originalFilePath);
    this.componentName = parsedPath.name;
    this.componentIdentifier = toPascalCaseIdentifier(this.componentName);
    this.parentDir = parsedPath.dir;
    this.originalExtension = parsedPath.ext;
    this.v1File = path.join(this.parentDir, `${this.componentName}.v1${this.originalExtension}`);
    this.versionsFile = path.join(this.parentDir, `${this.componentName}.versions.ts`);

    // Resolve export name: explicit flag > auto-detect
    this.exportName = this.resolveExportName(options.exportName);

    console.log(`Scaffolding forked component from: ${this.originalFilePath}`);
    console.log(`Component name: ${this.componentName}`);
    console.log(`Export: ${this.exportName === "default" ? "default" : `{ ${this.exportName} }`}`);
    console.log(`Target directory: ${this.parentDir}`);
  }

  resolveExportName(explicitExport) {
    if (explicitExport) {
      return explicitExport;
    }

    const fileContents = fs.readFileSync(this.originalFilePath, "utf8");
    const detection = detectComponentExport(fileContents);

    if (detection.type === "default") {
      return "default";
    }

    if (detection.type === "named") {
      return detection.name;
    }

    // Ambiguous — can't proceed without explicit flag
    const candidates = detection.candidates;
    const candidateList = candidates.length > 0
      ? candidates.join(", ")
      : "none found";

    const fileName = path.basename(this.originalFilePath);
    console.error(`Error: Can't determine which component to fork in ${fileName}`);
    console.error(`Found exported components: ${candidateList}`);
    console.error("");
    console.error("Specify the export to fork:");
    for (const c of candidates) {
      console.error(`  uifork init ${fileName} --export ${c}`);
    }
    if (!candidates.includes("default") && candidates.length > 0) {
      console.error(`  uifork init ${fileName} --export default`);
    }
    process.exit(1);
  }

  moveOriginalToV1() {
    fs.renameSync(this.originalFilePath, this.v1File);
    console.log(`Moved: ${path.basename(this.originalFilePath)} → ${path.basename(this.v1File)}`);
  }

  createVersionsFile() {
    const v1ImportPath = `./${this.componentName}.v1`;
    const importAlias = `${this.componentIdentifier}V1`;

    let importLine;
    if (this.exportName === "default") {
      importLine = `import ${importAlias} from "${v1ImportPath}"`;
    } else {
      importLine = `import { ${this.exportName} as ${importAlias} } from "${v1ImportPath}"`;
    }

    const versionsContent = `/**
 * THIS FILE IS GENERATED by uifork.
 * @uifork-export ${this.exportName}
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote ${this.componentName} <version-id>
 */
${importLine}

export const VERSIONS = {
  "v1": {
    render: ${importAlias},
    label: "",
  },
}
`;

    fs.writeFileSync(this.versionsFile, versionsContent);
    console.log(`Created: ${path.basename(this.versionsFile)}`);
  }

  createWrapper() {
    const versionsImportPath = `./${this.componentName}.versions`;
    const exportKeyword = this.exportName === "default" ? "export default" : "export";

    const wrapperContent = `"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., ${this.componentName}.v1${this.originalExtension}).
 * To stop versioning this component, run: npx uifork promote ${this.componentName} <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "${versionsImportPath}"

${exportKeyword} function ${this.componentIdentifier}(props: any) {
  return (
    <ForkedComponent
      id="${this.componentName}"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
`;

    const wrapperFile = path.join(this.parentDir, `${this.componentName}${this.originalExtension}`);
    fs.writeFileSync(wrapperFile, wrapperContent);
    console.log(`Created wrapper: ${path.basename(wrapperFile)}`);
  }

  scaffold() {
    this.moveOriginalToV1();
    this.createVersionsFile();
    this.createWrapper();

    const isNamed = this.exportName !== "default";

    console.log("\n✅ Scaffolding complete!");
    if (isNamed) {
      console.log(`\nEach version file must export the component as: export function ${this.exportName}...`);
    } else {
      console.log("\nEach version file must default-export its component.");
    }
    console.log("\nNext steps:");
    console.log(
      `1. Your original component is now ${this.componentName}.v1${this.originalExtension}`,
    );
    console.log(`2. UIFork will auto-initialize if you've set it up in your HTML.`);
    console.log(`   For Vite, add to your index.html <head>:`);
    console.log(`
   <script type="module">
     if (import.meta.env.DEV) {
       import("uifork/auto-init");
     }
   </script>
`);
    console.log(`   Or manually add <UIFork /> to your app root (only in development):`);
    console.log(`
   import { UIFork } from "uifork"
   import "uifork/style.css"
   
   function App() {
     return (
       <>
         <YourApp />
         {process.env.NODE_ENV === "development" && <UIFork />}
       </>
     )
   }
`);

    const importExample = isNamed
      ? `import { ${this.componentIdentifier} } from './${this.componentName}'`
      : `import ${this.componentIdentifier} from './${this.componentName}'`;

    if (this.shouldWatch) {
      console.log("3. Starting watch mode...");
      console.log(
        `4. Add new versions by creating ${this.componentName}.v2${this.originalExtension}, ${this.componentName}.v1_1${this.originalExtension}, etc.`,
      );
      console.log(`5. Import the component: ${importExample}`);
      new VersionSync(this.parentDir);
    } else {
      console.log(`3. Run: npx uifork watch (to start the watch server)`);
      console.log(
        `4. Add new versions by creating ${this.componentName}.v2${this.originalExtension}, ${this.componentName}.v1_1${this.originalExtension}, etc.`,
      );
      console.log(`5. Import the component: ${importExample}`);
    }
  }
}

module.exports = { UISwitcherScaffold };
