"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., ExplainerAnimation.v1.tsx).
 * To stop versioning this component, run: npx uifork promote ExplainerAnimation <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./ExplainerAnimation.versions"

export default function ExplainerAnimation(props: any) {
  return (
    <ForkedComponent
      id="ExplainerAnimation"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
