/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote ExplainerAnimation <version-id>
 */
import ExplainerAnimationV1 from "./ExplainerAnimation.v1"
import ExplainerAnimationV2 from "./ExplainerAnimation.v2"
import ExplainerAnimationV3 from "./ExplainerAnimation.v3"
import ExplainerAnimationV4 from "./ExplainerAnimation.v4"
import ExplainerAnimationV5 from "./ExplainerAnimation.v5"
import ExplainerAnimationV6 from "./ExplainerAnimation.v6"
import ExplainerAnimationV7 from "./ExplainerAnimation.v7"
import ExplainerAnimationV8 from "./ExplainerAnimation.v8"
export const VERSIONS = {
  "v1": {
    render: ExplainerAnimationV1,
    label: "",
  },
  "v2": {
    render: ExplainerAnimationV2,
    label: "",
  },
  "v3": {
    render: ExplainerAnimationV3,
    label: "",
  },
  "v4": {
    render: ExplainerAnimationV4,
    label: "",
  },
  "v5": {
    render: ExplainerAnimationV5,
    label: "",
  },
  "v6": {
    render: ExplainerAnimationV6,
    label: "",
  },
  "v7": {
    render: ExplainerAnimationV7,
    label: "",
  },
  "v8": {
    render: ExplainerAnimationV8,
    label: "",
  },
}
