/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote ExplainerAnimation <version-id>
 */
import ExplainerAnimationV1 from "./ExplainerAnimation.v1"
import ExplainerAnimationV2 from "./ExplainerAnimation.v2"
import ExplainerAnimationV3 from "./ExplainerAnimation.v3"
import ExplainerAnimationV4 from "./ExplainerAnimation.v4"
import ExplainerAnimationV5 from "./ExplainerAnimation.v5"
import ExplainerAnimationV6 from "./ExplainerAnimation.v6"
import ExplainerAnimationV7 from "./ExplainerAnimation.v7"
import ExplainerAnimationV8 from "./ExplainerAnimation.v8"
import ExplainerAnimationV9 from "./ExplainerAnimation.v9"
import ExplainerAnimationV10 from "./ExplainerAnimation.v10"
import ExplainerAnimationV11 from "./ExplainerAnimation.v11"
import ExplainerAnimationV12 from "./ExplainerAnimation.v12"
import ExplainerAnimationV13 from "./ExplainerAnimation.v13"
import ExplainerAnimationV14 from "./ExplainerAnimation.v14"
import ExplainerAnimationV15 from "./ExplainerAnimation.v15"
import ExplainerAnimationV16 from "./ExplainerAnimation.v16"
import ExplainerAnimationV17 from "./ExplainerAnimation.v17"
import ExplainerAnimationV18 from "./ExplainerAnimation.v18"
import ExplainerAnimationV19 from "./ExplainerAnimation.v19"
export const VERSIONS = {
  "v1": {
    render: ExplainerAnimationV1,
    label: "First pass",
  },
  "v2": {
    render: ExplainerAnimationV2,
    label: "Placeholder content",
  },
  "v3": {
    render: ExplainerAnimationV3,
    label: "Added mini ui",
  },
  "v4": {
    render: ExplainerAnimationV4,
    label: "",
  },
  "v5": {
    render: ExplainerAnimationV5,
    label: "",
  },
  "v6": {
    render: ExplainerAnimationV6,
    label: "",
  },
  "v7": {
    render: ExplainerAnimationV7,
    label: "",
  },
  "v8": {
    render: ExplainerAnimationV8,
    label: "",
  },
  "v9": {
    render: ExplainerAnimationV9,
    label: "",
  },
  "v10": {
    render: ExplainerAnimationV10,
    label: "",
  },
  "v11": {
    render: ExplainerAnimationV11,
    label: "Changing UIs",
  },
  "v12": {
    render: ExplainerAnimationV12,
    label: "",
  },
  "v13": {
    render: ExplainerAnimationV13,
    label: "Editing v4 file",
  },
  "v14": {
    render: ExplainerAnimationV14,
    label: "Compare at end",
  },
  "v15": {
    render: ExplainerAnimationV15,
    label: "Add text; Narrative",
  },
  "v16": {
    render: ExplainerAnimationV16,
    label: "",
  },
  "v17": {
    render: ExplainerAnimationV17,
    label: "",
  },
  "v18": {
    render: ExplainerAnimationV18,
    label: "",
  },
  "v19": {
    render: ExplainerAnimationV19,
    label: "",
  },
}
