/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote DashboardContent <version-id>
 */
import DashboardContentV1 from "./DashboardContent.v1"
import DashboardContentV2 from "./DashboardContent.v2"
export const VERSIONS = {
  "v1": {
    render: DashboardContentV1,
    label: "",
  },
  "v2": {
    render: DashboardContentV2,
    label: "",
  },
}
