/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote PromptTestTopSection <version-id>
 */
import PromptTestTopSectionV1 from "./PromptTestTopSection.v1"
export const VERSIONS = {
  "v1": {
    render: PromptTestTopSectionV1,
    label: "",
  },
}
