"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., PromptTestTopSection.v1.tsx).
 * To stop versioning this component, run: npx uifork promote PromptTestTopSection <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./PromptTestTopSection.versions"

export default function PromptTestTopSection(props: any) {
  return (
    <ForkedComponent
      id="PromptTestTopSection"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
